version: '3.8'
services:
  # run web service
  app:
    build: .
    image: fastapi-app
    container_name: app
    ports:
      - "8000:8000" # "local_port:default_image_port"
    volumes:
      - .:/fastapi-app #current_dir:default_image_dir

    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    container_name: fastapi-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fastapi_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: ""
    volumes:
        - ./db_data:/var/lib/mysql